<?php
/**
 * CSV Export Controller (Manager Only)
 * Restaurant Billing & Order Management System
 */

declare(strict_types=1);

require_once __DIR__ . '/BaseController.php';
require_once ROOT_PATH . '/models/Order.php';
require_once ROOT_PATH . '/models/Restaurant.php';

class ExportController extends BaseController {
    /**
     * Show Export Configuration Screen
     */
    public function index(): void {
        $user = $this->requireRole([User::ROLE_MANAGER, User::ROLE_SUPERADMIN]);
        $restaurantId = $this->requireRestaurantId();

        $restaurant = Restaurant::findById($restaurantId);
        $tz = new DateTimeZone($restaurant['timezone'] ?? 'Asia/Kolkata');
        $now = new DateTime('now', $tz);

        $this->render('manager/exports', [
            'title' => 'Export Data | DinePOS',
            'restaurant' => $restaurant,
            'todayDate' => $now->format('Y-m-d'),
            'currentMonth' => $now->format('Y-m'),
        ]);
    }

    /**
     * Generate and Download CSV Export
     */
    public function download(): void {
        $user = $this->requireRole([User::ROLE_MANAGER, User::ROLE_SUPERADMIN]);
        $restaurantId = $this->requireRestaurantId();

        $exportType = $_GET['type'] ?? 'daily';
        $restaurant = Restaurant::findById($restaurantId);
        $tz = new DateTimeZone($restaurant['timezone'] ?? 'Asia/Kolkata');
        $now = new DateTime('now', $tz);

        $startDate = $now->format('Y-m-d');
        $endDate = $now->format('Y-m-d');
        $filenameSuffix = $now->format('Ymd');

        if ($exportType === 'daily') {
            $date = $_GET['date'] ?? $now->format('Y-m-d');
            $startDate = $date;
            $endDate = $date;
            $filenameSuffix = "daily_{$date}";
        } elseif ($exportType === 'monthly') {
            $month = $_GET['month'] ?? $now->format('Y-m'); // e.g. 2026-08
            $dt = DateTime::createFromFormat('Y-m', $month, $tz) ?: $now;
            $startDate = $dt->format('Y-m-01');
            $endDate = $dt->format('Y-m-t');
            $filenameSuffix = "monthly_{$month}";
        } elseif ($exportType === 'custom') {
            $startDate = $_GET['start_date'] ?? $now->format('Y-m-d');
            $endDate = $_GET['end_date'] ?? $now->format('Y-m-d');
            $filenameSuffix = "custom_{$startDate}_to_{$endDate}";
        }

        // Fetch aggregate summary
        $stats = Order::getStats($restaurantId, 'custom', $startDate, $endDate);
        // Fetch detailed orders
        $orders = Order::getOrdersForExport($restaurantId, $startDate, $endDate);

        $sanitizedRestName = preg_replace('/[^a-zA-Z0-9_\-]/', '_', $restaurant['name'] ?? 'Restaurant');
        $filename = "{$sanitizedRestName}_orders_{$filenameSuffix}.csv";

        // Send CSV Download Headers
        header('Content-Type: text/csv; charset=UTF-8');
        header("Content-Disposition: attachment; filename=\"{$filename}\"");
        header('Pragma: no-cache');
        header('Expires: 0');

        $out = fopen('php://output', 'w');

        // Add UTF-8 BOM for Excel compatibility
        fprintf($out, chr(0xEF).chr(0xBB).chr(0xBF));

        // 1. Write Restaurant & Summary Header
        fputcsv($out, ['RESTAURANT SALES EXPORT REPORT']);
        fputcsv($out, ['Restaurant Name', $restaurant['name'] ?? '']);
        fputcsv($out, ['Export Range', "{$startDate} to {$endDate}"]);
        fputcsv($out, ['Generated At', $now->format('d M Y, h:i A') . " ({$restaurant['timezone']})"]);
        fputcsv($out, ['Generated By', $user['username'] . " ({$user['role']})"]);
        fputcsv($out, []); // Blank line

        // 2. Financial Summary
        fputcsv($out, ['FINANCIAL SUMMARY']);
        fputcsv($out, ['Total Orders', $stats['total_orders']]);
        fputcsv($out, ['Total Revenue (INR)', number_format($stats['total_sales'], 2, '.', '')]);
        fputcsv($out, ['Cash Sales (INR)', number_format($stats['cash_sales'], 2, '.', '')]);
        fputcsv($out, ['Online / UPI Sales (INR)', number_format($stats['online_sales'], 2, '.', '')]);
        fputcsv($out, []); // Blank line

        // 3. Orders Table Header
        fputcsv($out, [
            'Order #',
            'Order Date',
            'Order Time',
            'Customer Name',
            'Customer Phone',
            'Items Summary',
            'Total Items Count',
            'Subtotal (INR)',
            'Total (INR)',
            'Payment Method',
            'Status',
            'Billed By'
        ]);

        // 4. Order Rows
        foreach ($orders as $order) {
            $itemStrings = [];
            $totalQuantity = 0;
            foreach ($order['items'] as $item) {
                $qty = (float)$item['quantity'];
                $totalQuantity += $qty;
                $formattedQty = ($qty == (int)$qty) ? (string)(int)$qty : (string)$qty;
                $itemStrings[] = "{$item['item_name_snapshot']} ({$item['variant_name_snapshot']}) x {$formattedQty} {$item['unit']} = " . number_format((float)$item['total_price'], 2);
            }
            $itemsSummary = implode(' | ', $itemStrings);

            fputcsv($out, [
                $order['order_number'],
                $order['order_date'],
                $order['order_time'],
                $order['customer_name'] ?? 'Walk-in',
                $order['customer_phone'] ?? '',
                $itemsSummary,
                $totalQuantity,
                number_format((float)$order['subtotal'], 2, '.', ''),
                number_format((float)$order['total'], 2, '.', ''),
                $order['payment_method'],
                ucfirst($order['status']),
                $order['created_by_username']
            ]);
        }

        fclose($out);
        exit;
    }
}
