-- Seeds for Demo Setup
-- Password for all demo accounts: password123
-- Hash: $2y$10$1Pz6p3Lq90kYkWwL4w5c9eHkZ8P4nS6w8yq5E0l9zR6P5h2q4W3Gy (or dynamically generated by migrate.php)

-- 1. Create Demo Restaurant
INSERT INTO `restaurants` (`id`, `name`, `phone`, `address`, `timezone`, `status`, `created_at`, `updated_at`)
VALUES (1, 'The Royal Fork', '+91 98765 43210', '102 Flavor Street, Culinary Hub, Connaught Place, New Delhi', 'Asia/Kolkata', 'active', '2026-08-24 10:00:00', '2026-08-24 10:00:00');

-- 2. Create Users
-- Superadmin (no restaurant_id)
INSERT INTO `users` (`id`, `restaurant_id`, `username`, `password_hash`, `role`, `status`, `failed_login_attempts`, `locked_until`, `created_at`, `updated_at`)
VALUES (1, NULL, 'superadmin', '$2y$10$qR6Q5Qe3Mwqn.Yq7V2zQbeJv2SjFk0Klm5fAoeV8fG9mS0l9zR6P5', 'superadmin', 'active', 0, NULL, '2026-08-24 10:00:00', '2026-08-24 10:00:00');

-- Manager for Restaurant 1
INSERT INTO `users` (`id`, `restaurant_id`, `username`, `password_hash`, `role`, `status`, `failed_login_attempts`, `locked_until`, `created_at`, `updated_at`)
VALUES (2, 1, 'manager01', '$2y$10$qR6Q5Qe3Mwqn.Yq7V2zQbeJv2SjFk0Klm5fAoeV8fG9mS0l9zR6P5', 'manager', 'active', 0, NULL, '2026-08-24 10:00:00', '2026-08-24 10:00:00');

-- Cashier for Restaurant 1
INSERT INTO `users` (`id`, `restaurant_id`, `username`, `password_hash`, `role`, `status`, `failed_login_attempts`, `locked_until`, `created_at`, `updated_at`)
VALUES (3, 1, 'cashier01', '$2y$10$qR6Q5Qe3Mwqn.Yq7V2zQbeJv2SjFk0Klm5fAoeV8fG9mS0l9zR6P5', 'cashier', 'active', 0, NULL, '2026-08-24 10:00:00', '2026-08-24 10:00:00');

-- 3. Create Sample Items
-- Item 1: Chicken Curry (Portion)
INSERT INTO `items` (`id`, `restaurant_id`, `name`, `item_type`, `base_unit`, `active`, `created_at`, `updated_at`)
VALUES (1, 1, 'Chicken Curry', 'portion', 'portion', 1, '2026-08-24 10:00:00', '2026-08-24 10:00:00');

INSERT INTO `item_variants` (`id`, `item_id`, `variant_name`, `quantity_value`, `quantity_unit`, `price`, `active`, `created_at`, `updated_at`)
VALUES 
(1, 1, 'Full', 1.000, 'portion', 120.00, 1, '2026-08-24 10:00:00', '2026-08-24 10:00:00'),
(2, 1, 'Half', 0.500, 'portion', 60.00, 1, '2026-08-24 10:00:00', '2026-08-24 10:00:00'),
(3, 1, 'Quarter', 0.250, 'portion', 30.00, 1, '2026-08-24 10:00:00', '2026-08-24 10:00:00');

-- Item 2: Boiled Egg (Per Piece)
INSERT INTO `items` (`id`, `restaurant_id`, `name`, `item_type`, `base_unit`, `active`, `created_at`, `updated_at`)
VALUES (2, 1, 'Boiled Egg', 'piece', 'piece', 1, '2026-08-24 10:00:00', '2026-08-24 10:00:00');

INSERT INTO `item_variants` (`id`, `item_id`, `variant_name`, `quantity_value`, `quantity_unit`, `price`, `active`, `created_at`, `updated_at`)
VALUES 
(4, 2, 'Standard', 1.000, 'piece', 30.00, 1, '2026-08-24 10:00:00', '2026-08-24 10:00:00');

-- Item 3: Egg (Per Piece)
INSERT INTO `items` (`id`, `restaurant_id`, `name`, `item_type`, `base_unit`, `active`, `created_at`, `updated_at`)
VALUES (3, 1, 'Egg', 'piece', 'piece', 1, '2026-08-24 10:00:00', '2026-08-24 10:00:00');

INSERT INTO `item_variants` (`id`, `item_id`, `variant_name`, `quantity_value`, `quantity_unit`, `price`, `active`, `created_at`, `updated_at`)
VALUES 
(5, 3, 'Standard', 1.000, 'piece', 20.00, 1, '2026-08-24 10:00:00', '2026-08-24 10:00:00');

-- Item 4: Rice (Weight: kg)
INSERT INTO `items` (`id`, `restaurant_id`, `name`, `item_type`, `base_unit`, `active`, `created_at`, `updated_at`)
VALUES (4, 1, 'Rice', 'weight', 'kg', 1, '2026-08-24 10:00:00', '2026-08-24 10:00:00');

INSERT INTO `item_variants` (`id`, `item_id`, `variant_name`, `quantity_value`, `quantity_unit`, `price`, `active`, `created_at`, `updated_at`)
VALUES 
(6, 4, '1 kg', 1.000, 'kg', 120.00, 1, '2026-08-24 10:00:00', '2026-08-24 10:00:00');

-- Item 5: Cold Drink (Volume: Liter)
INSERT INTO `items` (`id`, `restaurant_id`, `name`, `item_type`, `base_unit`, `active`, `created_at`, `updated_at`)
VALUES (5, 1, 'Cold Drink', 'weight', 'l', 1, '2026-08-24 10:00:00', '2026-08-24 10:00:00');

INSERT INTO `item_variants` (`id`, `item_id`, `variant_name`, `quantity_value`, `quantity_unit`, `price`, `active`, `created_at`, `updated_at`)
VALUES 
(7, 5, '1 Liter', 1.000, 'l', 100.00, 1, '2026-08-24 10:00:00', '2026-08-24 10:00:00');
